### ISSUE TITLE
Wish "materialdesignicons" as another FontIcon library

### ISSUE THREAD

**Issue by StevenKRT** [AppoloDev/vanilla-icon-picker#1]
Add "materialdesignicons" as another FontIcon library. In the options you can then choose whether you want "fontawesome" or "materialdesignicons" or both activated.

https://materialdesignicons.com/

**Comment by simonmnt** [comment]
Sure, the feature is in preparation.

**Comment by simonmnt** [comment]
Material design icons is now available, check README for more informations.
