### ISSUE TITLE
Search icons with iconify categories

### ISSUE THREAD

**Issue by anthonyccf** [AppoloDev/vanilla-icon-picker#32]
Some icon sets are provided with categories in json files to allow the search of icons by keywords. 

An example of json with categories is provided below: 
https://github.com/iconify/icon-sets/blob/master/json/fa6-solid.json

Is there any way to search icons by the keywords in the categories using the icon picker search textbox?

**Comment by simonmnt** [comment]
Hi @anthonyccf,

Search by categories is now available.

**Comment by anthonyccf** [comment]
Hi @simonmnt 

Thx for your help! It works!
